config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('core.urls')), 
    path ('', include('accounts.urls')), 
    path ('', include('inventory.urls')), 
    path ('', include('order.urls')), 

    # path('markdownx/', include('markdownx.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# else:
#     urlpatterns += path('taksit-admin/', admin.site.urls),

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required, permission_required
from .views import IndexView
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

order/urls.py
from django.urls import path
from . import views 
from .views import client_order_create,client_order_edit, add_new_item,clientOrderBcListView,clientOrderFfListView,clientOrderBlListView, ClientOrderDetailView, ClientCustomPrintableView, warehouse_order_create, WarehouseOrderBcListView, WarehouseOrderFfListView,  WarehouseOrderBlListView, WarehouseOrderDetailView, WarehouseCustomPrintableView, create_supplier_order, SupplierOrderBcListView, SupplierOrderBrListView, AddSupplierView,SupplierListView, SupplyOrderDetailView, SupplierCustomPrintableView , DeliveryListView, warehouse_order_edit, htmx_order_bc_list
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'order' 
 
urlpatterns = [
  
   path('add_new_item', add_new_item, name="add_new_item"),
   #commandes interne  
   path('warehouse_order_create', login_required(warehouse_order_create), name="warehouse_order_create"),
   path('warehouse_order_edit/<int:pk>', login_required(warehouse_order_edit), name="warehouse_order_edit"),
   path('warehouse_order_bc_list', login_required(WarehouseOrderBcListView.as_view()), name="warehouse_order_bc_list"),
   path('htmx_order_bc_list', login_required(htmx_order_bc_list), name="htmx_order_bc_list"),
   path('warehouse_order_ff_list', login_required(WarehouseOrderFfListView.as_view()), name="warehouse_order_ff_list"),
   path('warehouse_order_bl_list', login_required(WarehouseOrderBlListView.as_view()), name="warehouse_order_bl_list"),
   path('warehouseorder_detail/<int:pk>/', login_required(WarehouseOrderDetailView.as_view()), name="warehouseorder_detail"),
   path('warehouseorderpdf/<int:pk>/', login_required(WarehouseCustomPrintableView.as_view()), name="warehouseorderpdf"),
   #commandes fournisseur 
   path('create_supplier_order', login_required(create_supplier_order), name="create_supplier_order"),
   path('addsupplier', login_required(AddSupplierView.as_view()), name="addsupplier"),
   path('supplierlist', login_required(SupplierListView.as_view()), name="supplierlist"),
   path('supplier_order_bc_list', login_required(SupplierOrderBcListView.as_view()), name="supplier_order_bc_list"),
   path('supplier_order_br_list', login_required(SupplierOrderBrListView.as_view()), name="supplier_order_br_list"),
   path('supplyorder_detail/<int:pk>/', login_required(SupplyOrderDetailView.as_view()), name="supplyorder_detail"),
   path('supplyorderpdf/<int:pk>/', login_required(SupplierCustomPrintableView.as_view()), name="supplyorderpdf"),
   #commandes client 
   path('create_client_order', login_required(client_order_create), name="client_order_create"),
   path('client_order_edit', login_required(client_order_edit), name="client_order_edit"),
   path('client_order_bc_list', login_required(clientOrderBcListView.as_view()), name="client_order_bc_list"),
   path('client_order_ff_list', login_required(clientOrderFfListView.as_view()), name="client_order_ff_list"),
   path('client_order_bl_list', login_required(clientOrderBlListView.as_view()), name="client_order_bl_list"),
   path('clientorder_detail/<int:pk>/', login_required(ClientOrderDetailView.as_view()), name="clientorder_detail"),
   path('clientorderpdf/<int:pk>/', login_required(ClientCustomPrintableView.as_view()), name="clientorderpdf"),
   ## livraison  
   path('delivery_list', login_required(DeliveryListView.as_view()), name="delivery_list"),
]

order/models.py
from django.db import models
from django.urls import reverse
import inventory
# Create your models here.
from django.conf import settings
from inventory.models import WareHouseItem
from location.models import Commune
import datetime
from django.db.models import Sum


TYPE_CHOICES = (
    ('BC' ,'Bon de commande'),
    ('FF' ,'Facture finale'),
    ('BL' ,'Bon de livraison'),
)


class OrderManager(models.Manager):
    def invoices(self):
        return WareHouseOrder.objects.filter(order_type="FF")

################# DELIVERY  #################
        

class WareHouseOrder(models.Model):
    # sender = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="sender", on_delete=models.CASCADE, related_name="set_orders")
    receiver  = models.ForeignKey("inventory.WareHouse", verbose_name="Depot de récéption", on_delete=models.CASCADE, related_name="warehouse_orders", null=True, blank=True)
    delivery_man  = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="livreur", on_delete=models.CASCADE, related_name="warehouse_orders_to_deliver", null=True, blank=True)
    order_type    = models.CharField(choices=TYPE_CHOICES,verbose_name="type de commande", max_length=2, null=True, blank=True)
    number        = models.IntegerField(verbose_name="numéro", null=True, blank=True)
    is_confirmed  = models.BooleanField(default=False)
    is_paid       = models.BooleanField(default=False)
    is_delivered  = models.BooleanField(default=False)
    is_return     = models.BooleanField(default=False)
    discount      = models.DecimalField(verbose_name="remise", max_digits=10, decimal_places=2, null=True, blank=True)
    delivery_cost =  models.DecimalField(verbose_name="cout de livraison", max_digits=10, decimal_places=2, null=True, blank=True)
    note          = models.TextField(null=True, blank=True)
    created_by      = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Creer par", on_delete=models.CASCADE,related_name="warehouse_orders_created", null=True, blank=True)
    updated_by      = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Modifier par", on_delete=models.CASCADE, related_name="warehouse_orders_updated", null=True, blank=True)
    created       = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated       = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    class Meta:
        ordering= ('-created',)
        verbose_name ="warehouseorder"
        verbose_name_plural = "warehouseorders"

    def __str__(self): 
        return str(self.receiver)

    def get_absolute_url(self):
        return reverse("order:warehouse_order_detail", kwargs={"pk": self.pk})

    @property
    def status(self):
        if self.is_return:
            return "Retour"
        else: 
            return "Retour"

    @property
    def invoice_num(self):
        try:
            last_num = WareHouseOrder.invoices.latest("number")
            self.number = last_num + 1
        except:
            self.number = 1
        the_num = self.number
        # the_num = str(self.number).zfill(5)
        date = datetime.date.today()
        year = date.strftime("%Y")
        return f"N°: {the_num}/{year}"
        # return f"N°: {the_num:03d}/{year}"

    def get_items_cost(self):
        total = self.items.all().aggregate(Sum('price'))
        return total['price__sum']

    @property
    def get_price(self):
        return self.price * self.quantity
        # try:
        # except:
        #     return 0
    # def save(self, *args, **kwargs):
    #     return sum(item.get_price() for item in self.items.all())
    
    # def get_items_price(self):
    #     items_cost = sum(item.get_price() for item in self.items.all())
    #     return items_cost
    # def get_total_price(self):
    #     items_cost = sum(item.get_price() for item in self.items.all())
    #     total_cost = items_cost - self.discount
    #     return total_cost


class WareHouseOrderItem(models.Model):
    order           = models.ForeignKey(WareHouseOrder, verbose_name="Commande", on_delete=models.CASCADE, related_name="items")
    warehouse_item  = models.ForeignKey("inventory.WareHouseItem", verbose_name="produit", on_delete=models.CASCADE, related_name="warehouse_order_items")
    quantity        = models.IntegerField(verbose_name="quantité", default=1)
    price           = models.DecimalField(verbose_name="prix", max_digits=10, decimal_places=2, null=True, blank=True)
    created         = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated         = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    def __str__(self):
        return str(f"{self.warehouse_item} - {self.warehouse_item.location}")

    @property
    def get_price(self):
        try:
            return self.price * self.quantity
        except:
            return 0

    @property
    def get_warehouse(self):
        return WareHouseItem.location





#################


class ClientOrder(models.Model):
    # sender          = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="sender", on_delete=models.CASCADE, related_name="set_client_orders")
    delivery_man = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="livreur", on_delete=models.CASCADE, related_name="client_orders", null=True, blank=True)
    first_name      = models.CharField(verbose_name="Nom" , max_length=50, null=True, blank=True)
    last_name       = models.CharField(verbose_name="Prenom" , max_length=50, null=True, blank=True)
    address         = models.CharField(verbose_name="Adresse" , max_length=250, null=True, blank=True)
    phone           = models.CharField(verbose_name="Téléphone" , max_length=25)
    email           = models.EmailField(verbose_name="E-mail", null=True, blank=True)
    commune         = models.ForeignKey(Commune, on_delete=models.SET_NULL, null=True, blank=True)
    order_type      = models.CharField(choices=TYPE_CHOICES,verbose_name="type de commande", max_length=2, null=True, blank=True)
    is_confirmed    = models.BooleanField(default=False)
    is_paid         = models.BooleanField(default=False)
    is_delivered    = models.BooleanField(default=False)
    is_cib          = models.BooleanField(default=False)
    cib_order_code  = models.CharField(verbose_name="code de commande cib", max_length=2, null=True, blank=True)
    coupon          = models.CharField(verbose_name="coupon", max_length=2, null=True, blank=True)
    is_return       = models.BooleanField(default=False)
    discount        = models.DecimalField(verbose_name="remise", max_digits=10, decimal_places=2, null=True, blank=True)
    delivery_cost   =  models.DecimalField(verbose_name="cout de livraison", max_digits=10, decimal_places=2, null=True, blank=True)
    note            = models.TextField(null=True, blank=True)
    created         = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated         = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)
    class Meta:
        verbose_name = "ClientOrder"
        verbose_name_plural = "ClientOrders"

    def __str__(self):
        return self.last_name

    def get_absolute_url(self):
        return reverse("order:client_order_detail", kwargs={"pk": self.pk})

class ClientOrderItem(models.Model):
    order           = models.ForeignKey(ClientOrder, verbose_name="commande", on_delete=models.CASCADE, related_name="client_orders")
    warehouse_item  = models.ForeignKey("inventory.WareHouseItem", verbose_name="produit", on_delete=models.CASCADE, related_name="client_order_items")
    quantity        = models.IntegerField(verbose_name="quantité", default=1)
    price           = models.DecimalField(verbose_name="prix", max_digits=10, decimal_places=2, null=True, blank=True)
    created      = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)
    def get_absolute_url(self):
        return reverse("order:client_order_item_detail", kwargs={"pk": self.pk})

    @property
    def get_warehouse(self):
        return warehouse_item.location

################# SUPPLY  #################

class Supplier(models.Model):
    name    = models.CharField(verbose_name="Nom du fournisseur", max_length=150, null=True, blank=True)
    adress  = models.CharField(verbose_name="Adresse du fournisseur", max_length=150, null=True, blank=True)
    rc_code = models.CharField(verbose_name="numéro du registre de commerce", max_length=150, null=True, blank=True)
    art_code= models.CharField(verbose_name="numéro d'article", max_length=150, null=True, blank=True)
    nif_code= models.CharField(verbose_name="numéro identité fiscale", max_length=150, null=True, blank=True)
    nis_code= models.CharField(verbose_name="Numéro d’Identification Statistique", max_length=150, null=True, blank=True)
    created      = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    class Meta:
        verbose_name ="supplier"
        verbose_name_plural ="suppliers"

    def __str__(self):
        return  str(self.name)

    def get_absolute_url(self):
        return reverse("order:supplier_detail", kwargs={"pk": self.pk})

class SupplyOrder(models.Model):
    supplier = models.ForeignKey(Supplier, verbose_name="sender", on_delete=models.CASCADE, related_name="sent_orders")
    receiver = models.ForeignKey("inventory.WareHouse", verbose_name="receiver", on_delete=models.CASCADE, related_name="supply_orders", null=True, blank=True)
    is_paid = models.BooleanField(default=False)
    is_received = models.BooleanField(default=False)
    is_return = models.BooleanField(default=False)

order/forms.py
from django import forms
from django.forms import ModelForm
from .models import WareHouseOrder, WareHouseOrderItem 
from .models import Supplier, SupplyOrder, SupplyOrderItem
from .models import ClientOrderItem, ClientOrder
from django.forms.models import inlineformset_factory, modelformset_factory



class WareHouseOrderForm(ModelForm) :
    class Meta: 
        model = WareHouseOrder
        fields = ('receiver', 'delivery_man', 'order_type', 'is_confirmed', 'is_paid', 'is_delivered', 'is_return', 'discount', 'delivery_cost', 'note')

class WareHouseOrderItemForm(ModelForm) :
    # custom = forms.IntegerField(required=False)
    class Meta: 
        model = WareHouseOrderItem
        fields = ("order","warehouse_item","quantity","price",)

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
        # self.fields['custom'] = forms.IntegerField()

class ProductInternalOrder(forms.Form):
    product = forms.CharField( required=True)
    quantity = forms.IntegerField()
    # reference = 

#fournisseur 
class SupplyOrderForm(ModelForm) :
    class Meta: 
        model = SupplyOrder
        fields = '__all__'

class SupplierForm(ModelForm) :
    class Meta: 
        model = Supplier
        fields = '__all__'

class SupplyOrderItemForm(ModelForm) :
    custom = forms.IntegerField(required=False)
    class Meta: 
        model = SupplyOrderItem
        fields = ("order","warehouse_item","quantity","price",)

#client 
class ClientOrderForm(ModelForm) :
    class Meta: 
        model = ClientOrder
        fields = '__all__'

class ClientOrderItemForm(ModelForm) :
    custom = forms.IntegerField(required=False)
    class Meta: 
        model = ClientOrderItem
        fields = ("order","warehouse_item","quantity","price",)

from django.forms import BaseModelFormSet
class BaseAuthorFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.queryset = WareHouseOrderItem.objects.filter().distinct('warehouse_item')


WarehouseOrderItemFormSet = inlineformset_factory(
    WareHouseOrder,
    WareHouseOrderItem,
    fields=("warehouse_item","quantity",),
    form = WareHouseOrderItemForm,
    formset=BaseAuthorFormSet,
    min_num=1, 
    extra=0,
)

order/templates/client_order_create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Commandes</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Commandes
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Ajout d'une commande client</h4>
                <form action="{% url 'order:create_client_order' %}" method="post"  class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                   
                  </p>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_first_name">Nom</label>
                        <div class="col-sm-9"> 
                            <input type="text" name="first_name" class="form-control" maxlength="50" id="id_first_name">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_last_name">Prénom</label>
                          <div class="col-sm-9"> 
                            <input type="text" name="last_name" class="form-control" maxlength="50" id="id_last_name">
                          </div>
                        </div>
                      </div>
                
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_address">Adresse </label>
                      <div class="col-sm-9"> 
                        <input type="text" name="address" class="form-control" maxlength="50" id="id_address">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_commune">Commune </label>
                      <div class="col-sm-9"> 
                        <select name="commune" id="id_commune" class="form-control">
                            <option>Selectionner une commune</option>
                            {% for commune in communes %}
                            <option  value="{{commune.id}}">{{commune.name}}</option>
                            {% endfor %}
                          </select>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_phone">Téléphone </label>
                      <div class="col-sm-9"> 
                        <input type="text" name="phone" class="form-control" maxlength="25" required="" id="id_phone">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_email">E-mail </label>
                      <div class="col-sm-9"> 
                        <input type="email" name="email" class="form-control" maxlength="254" id="id_email">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                        <div class="col-sm-4">
                            <div class="form-check form-check-primary">
                                <label class="form-check-label" for="id_is_confirmed">
                                    Confirmé 
                                  <input type="checkbox" class="form-check-input" checked="" name="is_confirmed" id="id_is_confirmed" > 
                                <i class="input-helper"></i></label>
                            </div>
                        </div>
                          <div class="col-sm-4">
                              <div class="form-check form-check-primary">
                                  <label class="form-check-label" for="id_is_paid">
                                      Payé 
                                    <input type="checkbox" class="form-check-input" checked="" name="is_paid" id="id_is_paid" > 
                                  <i class="input-helper"></i></label>
                              </div>
                          </div>
                          <div class="col-sm-4">
                            <div class="form-check form-check-primary">
                                <label class="form-check-label" for="id_is_return">
                                    Retour 
                                  <input type="checkbox" class="form-check-input" checked="" name="is_return" id="id_is_return" > 
                                <i class="input-helper"></i></label>
                            </div>
                        </div>
                          <div class="col-sm-4">
                            <div class="form-check form-check-primary">
                                <label class="form-check-label" for="id_is_cib">
                                 CIB 
                                  <input type="checkbox" class="form-check-input" checked="" name="is_cib" id="id_is_cib" > 
                                <i class="input-helper"></i></label>
                            </div>
                        </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_cib_order_code">Code de commande cib </label>
                      <div class="col-sm-9"> 
                        <input type="text" name="cib_order_code" class="form-control" maxlength="2" id="id_cib_order_code">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_coupon">Coupon </label>
                      <div class="col-sm-9"> 
                        <input type="text" name="coupon"  class="form-control" maxlength="2" id="id_coupon">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_discount">Remise </label>
                      <div class="col-sm-9"> 
                        <input type="number" name="discount" class="form-control" step="0.01" id="id_discount">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_delivery_cost">Cout de livraison </label>
                      <div class="col-sm-9"> 
                        <input type="number" name="delivery_cost" step="0.01" class="form-control" id="id_delivery_cost">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_delivery_man">Livreur </label>
                      <div class="col-sm-9"> 
                        <select name="delivery_man" id="id_delivery_man" class="form-control">
                            <option>Selectionner un livreur</option>
                            {% for delivery in deliverys %}
                            <option  value="{{delivery.id}}">{{delivery.warehouse}}</option>
                            {% endfor %}
                          </select>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label class="col-sm-3 col-form-label" for="id_note">Note </label>
                      <div class="col-sm-9"> 
                        <textarea name="note" cols="40" rows="10" class="form-control" id="id_note"></textarea>
                      </div>
                    </div>
                  </div>
              </div>
                  <p class="card-description">
                    Produits
                  </p>
                <!--table -->
                <div class="row">
                    <div class="col-12 grid-margin">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-md-flex justify-content-between align-items-center">
                                    <table >
                                    <thead>
                                        <tr role="row">
                                            <th style="width:400px;" for="id_items-{{forloop.counter0}}-warehouse_item">Produit </th>                                           
                                            <th style="width:400px;" for="id_items-{{forloop.counter0}}-quantity">Quantité</th>
                                            <th style="width:400px; padding:10px;" for="id_items-{{forloop.counter0}}-DELETE"><i class="fas fa-trash"></i></th> 
                                            <th style="width:100px;"></th>
                                        </tr>
                                    </thead>
                                    <tbody id="form-container" > 
                                      {{ formset.management_form }}
                                      {% for form in formset %}
                                              <tr class="item-form ">
                                        <td >
                                            <select name="items-{{forloop.counter0}}-warehouse_item" class="form-control" id="id_items-{{forloop.counter0}}-warehouse_item" required>
                                                <option>Selectionner un Produit</option>
                                                {% for product in products %}
                                                <option value="{{product.id}}">{{product}}</option>
                                                {% endfor %}
                                            </select> 
                                        </td>
                                        <td >
                                            <input type="number" name="items-{{forloop.counter0}}-quantity"class="form-control" id="id_items-{{forloop.counter0}}-quantity">
                                        <td  style=" padding:10px">
                                            <input type="checkbox" name="items-{{forloop.counter0}}-DELETE" id="id_items-{{forloop.counter0}}-DELETE">
                                        </td>
                                        <td></td>
                                      </tr> 
                                        {% endfor %}
                                </tbody>
                          
                            </table>
                            <button type="submit" id="add-form" class="btn btn-primary mr-2" style="right:50px"> + </button> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'order:create_client_order' %}"> <button type="submit" class="btn btn-primary mr-2">Submit</button> </a>
                </div>
            </form>
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}

  {% block extrasj %}
  <script>
      var itemForm = document.querySelectorAll(".item-form")
      var container = document.querySelector("#form-container") 
      let addButton = document.querySelector("#add-form")
      var totalForms = document.querySelector("#id_items-TOTAL_FORMS")
  
      let formNum = itemForm.length-1
      addButton.addEventListener('click', addForm)
      console.log('yeess')
  
      function addForm(e){
          console.log('iniiiiiiit')
          e.preventDefault()
          let newForm = itemForm[0].cloneNode(true)
          let formRegex = RegExp(`items-(\\d){1}-`,'g')
          formNum++
          newForm.innerHTML = newForm.innerHTML.replace(formRegex, `items-${formNum}-`)
          container.append(newForm) 
          totalForms.setAttribute('value', `${formNum+1}`)
      }
     
  </script>
  {% endblock extrasj %}