accounts/urls.py
from django.urls import path
from .views import SignupView, SignupsuccessView
from django.contrib.auth import views as auth_views
from .froms import AuthenticationForm
from django.contrib.auth.decorators import login_required, permission_required
from .views import UserView, UserUpdateView
app_name= 'accounts'

urlpatterns = [
  
 path('signup/', SignupView.as_view(), name="signup"),
 path('signup_success/', SignupsuccessView.as_view(), name="signup_success"),
 path('login/', auth_views.LoginView.as_view(template_name="login.html",form_class=AuthenticationForm,),name="login",),
 path('logout/' , auth_views.LogoutView.as_view(), name= 'logout' ),
 path('userdetail', login_required(UserView.as_view()), name="userdetail"),
 path('edituser/<int:pk>/', login_required(UserUpdateView.as_view()), name="edituser"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('core.urls')), 
    path ('', include('accounts.urls')), 
    path ('', include('inventory.urls')), 
    path ('', include('order.urls')), 

    # path('markdownx/', include('markdownx.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# else:
#     urlpatterns += path('taksit-admin/', admin.site.urls),

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required, permission_required
from .views import IndexView
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (AbstractUser, BaseUserManager)
from inventory.models import WareHouse 
# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password,**extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields) 
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        extra_fields.setdefault("is_active", False)
        return self._create_user(email, password, **extra_fields)
       
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        if extra_fields.get("is_staff") is not True:
         raise ValueError(
                "Superuser must have is_staff=True."
        )
        if extra_fields.get("is_active") is not True:
         raise ValueError(
                "Superuser must have is_active=True."
        )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                 "Superuser must have is_superuser=True."
        )
        return self._create_user(email, password, **extra_fields)
    
class CustomUserManager(models.Manager):

    def user_warehouses(self):
        return User.objects.filter(warehouse__isnull=False, is_active=True, is_manager=True)

class User(AbstractUser):
    username        = None
    email           = models.EmailField('email address', unique=True)
    picture         = models.ImageField(upload_to='images/faces', null=True, blank=True)
    pseudo          = models.CharField( max_length=150, null=True, blank=True)
    role            = models.CharField( max_length=150, null=True, blank=True)
    notes           = models.TextField( blank=True, null=True)
    warehouse       = models.ForeignKey(WareHouse, on_delete=models.SET_NULL, blank=True, null=True)
    is_active       = models.BooleanField(default=False)
    is_manager      = models.BooleanField(default=False)
    is_admin        = models.BooleanField(default=False)
    USERNAME_FIELD  = 'email'
    REQUIRED_FIELDS = []
    objects         = UserManager()
    custom_objects  = CustomUserManager()

    def display_picture(self):
        if self.picture:
            return self.picture.url
        else: 
            return "static/images/profile.png" 

    @property
    def is_assistant(self):
        return self.is_active and (self.is_superuser or self.is_staff and self.groups.filter(name="Assistant").exists())
    @property
    def is_developer(self):
        return self.is_active and (self.is_superuser or self.is_staff and self.groups.filter(name="Developer").exists())
    @property
    def is_commercial(self):
        return self.is_active and (self.is_superuser or self.is_staff and self.groups.filter(name="Commercial").exists())
    @property
    def is_marketer(self):
        return self.is_active and (self.is_superuser or self.is_staff and self.groups.filter(name="Marketer").exists() )
    @property
    def is_content_creator(self):
        return self.is_active and (self.is_superuser or self.is_staff and self.groups.filter(name="Content_creator").exists())

    class Meta:
        unique_together = ('is_manager', 'warehouse')

accounts/views.py
from pipes import Template
from pprint import pprint
from django.shortcuts import render
import logging
from django.contrib.auth import login, authenticate
from django.contrib.messages import constants as messages
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin as DjangoUserAdmin
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.views.generic import UpdateView
from accounts.models import User
from .froms import UserCreationForm, UserEditForm
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils.functional import lazy
# Create your views here.
# logger = logging.getLogger(__name__)

class SignupView(FormView):
    template_name = "signup.html"
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:signup_success')
    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        return response    

class SignupsuccessView(TemplateView):
    template_name = "signup_message.html" 


class UserView(TemplateView):
    model = User
    template_name= "user-detail.html"
  

class UserUpdateView(UpdateView):
    model = User
    form_class= UserEditForm
    template_name = 'edit-user.html' 
    success_url = reverse_lazy('accounts:userdetail')
    def form_invalid(self, form):
        pprint(form.errors)
        return super().form_invalid(form)
   

accounts/templates/edit-user.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Compte</title>
{% endblock %}

<div class="content-wrapper">
  <div class="page-header">
      <h3 class="page-title">
        Compte
      </h3>
  </div> 
  <div class="col-12 grid-margin">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Modifier votre compte</h4>
        <form action="{% url 'accounts:edituser' user.pk %}"  method="post"  class="form-sample">
            {% csrf_token %}
          <p class="card-description">
          </p>
          <div class="row">
         
                <div class="col-md-6">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label" for="id_pseudo">Nom :</label>
                    <div class="col-sm-9">
                    <input  type="text" name="pseudo"  id="id_pseudo"  required="" class="form-control"  value="{{user.pseudo}}">
                    </div>
                </div>
                </div>
                <div class="col-md-6">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label" for="id_role">Role :</label>
                    <div class="col-sm-9">
                    <input type="text" name="role" class="form-control " maxlength="150" required="" id="id_role" value="{{user.role}}"> 
                    </div>
                </div>
                </div>
                
                <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_picture">Photo :</label>
                        <div class="input-group col-sm-9">
                            <input type="text" class="form-control file-upload-info"  name="picture"  id="id_picture"  disabled="" placeholder="Upload Image">
                            <span class="input-group-append">
                              <button class="file-upload-browse btn btn-primary" type="file">Upload</button>
                            </span>
                        </div>
                        
                    </div>
                    </div>
                   
          </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
        </form>
      </div>
    </div>
  
  </div> 
  <!-- main-panel ends -->
</div>

{% endblock content %}

accounts/templates/login.html
{% load static %}
{% block content %}
{% block title %}
<title>Login</title>
{% endblock %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
  </head>
  
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row w-100">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <img src="{% static 'images/logo.png' %}" alt="logo" style="width:400px; heght400px;">
                </div>
                <h6 class="font-weight-light">Connectez-vous pour continuer.</h6>
                <form class="pt-3" method="post" action="."> 
                  {% csrf_token %}  
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        {{ form.email.label_tag }}
                        <input type="email" class="form-control {% if form.email.errors %} is-invalid{% endif %}" id="id_email" name="email" placeholder="votre email" value="{{ form.email.value|default:"" }}"> {% if form.email.errors %}
                        <div class="invalid-feedback">
                        {{ form.email.errors }}
                        </div>
                        {% endif %}
                    </div>
                  <div class="form-group">
                    {{ form.password.label_tag }}
                    <input type="password" class="form-control{% if form.password.errors %}  is-invalid{% endif %}" id="id_password" name="password" value="{{ form.password.value|default:"" }}"> {% if form.password.errors %}
                      <div class="invalid-feedback">
                      {{ form.password.errors }}
                      </div>
                    {% endif %}
                  </div>                                  
                  <div class="mt-3">
                    <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">CONNEXION</button>
                  </div>
                  <div class="my-2 d-flex justify-content-between align-items-center">
                  <div class="text-center mt-4 font-weight-light">
                    Vous n'avez pas de compte ? <a href="{% url 'accounts:signup' %}" class="text-primary">créer un compte</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="{% static 'js/off-canvas.js' %}"></script>
    <script src="{% static 'js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'js/misc.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/todolist.js' %}"></script>
    <!-- endinject -->
  </body>


{% endblock content %}

accounts/templates/signup.html
{% load static %}
{% block content %}
{% block title %}
<title>Signup</title>
{% endblock %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row w-100">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <img src="{% static 'images/logo.png' %}" alt="logo" style="width:400px; heght400px;">
                </div>
                <h6 class="font-weight-light">créer un compte</h6>
                <form class="pt-3" action="" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    {{ form.email.label_tag }}
                    <input type="email" class="form-control {% if form.email.errors %}  is-invalid{% endif %}" id="id_email" name="email" placeholder="Votre email" value="{{ form.email.value|default:"" }}" > {% if form.email.errors %}
                      <div class="invalid-feedback">
                          {{ form.email.errors }}
                        </div>
                        {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.password1.label_tag }}
                      <input type="password" class="form-control {% if form.password1.errors %}  is-invalid{% endif %}" id="id_password1" name="password1" value="{{ form.password1.value|default:"" }}"> {% if form.password1.errors %}
                        <div class="invalid-feedback">
                          {{ form.password1.errors }}
                        </div>
                        {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.password2.label_tag }}
                      <input type="password" class="form-control{% if form.password2.errors %}  is-invalid{% endif %}" id="id_password2" name="password2" value="{{ form.password2.value|default:"" }}"> {% if form.password2.errors %}
                        <div class="invalid-feedback">
                           {{ form.password2.errors }}
                         </div>
                        {% endif %}
                    </div>
                  <div class="mb-4">
                  </div>
                  <div class="mt-3">
                    <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">S'INSCRIRE</button>
                  </div>
                  <div class="text-center mt-4 font-weight-light">
                    Vous avez déjà un compte? <a href="{% url 'accounts:login' %}" class="text-primary">connectez-vous</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->


   <!-- plugins:js -->
   <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
   <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
   <!-- endinject -->
   <!-- inject:js -->
   <script src="{% static 'js/off-canvas.js' %}"></script>
   <script src="{% static 'js/hoverable-collapse.js' %}"></script>
   <script src="{% static 'js/misc.js' %}"></script>
   <script src="{% static 'js/settings.js' %}"></script>
   <script src="{% static 'js/todolist.js' %}"></script>
   <!-- endinject -->
 </body>


{% endblock content %}

accounts/templates/signup_message.html
{% load static %}
{% block content %}
{% block title %}
<title>Signup</title>
{% endblock %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row w-100">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <img src="{% static 'images/logo.png' %}" alt="logo" style="width:400px; heght400px;">
                </div>
                <h4>vous avez créer un compte avec succès</h4>
                <h6 class="font-weight-light">Malheureusement, vous ne pouvez pas vous connecter.</h6>
                <h6 class="font-weight-light">Veuillez patienter pendant que des privilèges vous sont accordés.</h6>

              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->


   <!-- plugins:js -->
   <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
   <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
   <!-- endinject -->
   <!-- inject:js -->
   <script src="{% static 'js/off-canvas.js' %}"></script>
   <script src="{% static 'js/hoverable-collapse.js' %}"></script>
   <script src="{% static 'js/misc.js' %}"></script>
   <script src="{% static 'js/settings.js' %}"></script>
   <script src="{% static 'js/todolist.js' %}"></script>
   <!-- endinject -->
 </body>


{% endblock content %}

accounts/templates/user-detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Compte</title>
{% endblock %}

<div class="content-wrapper">
  <div class="page-header">
      <h3 class="page-title">
        Compte
      </h3>
  </div> 
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-4">
              <div class="border-bottom text-center pb-4">
                <img src="{{user.display_picture}}" alt="profile" class="img-lg rounded-circle mb-3">
                <p></p>
              </div>
              <div class="border-bottom  py-4">
                <div class="py-4">
                  <p class="clearfix">
                    <span class="float-left">
                      Role
                    </span>
                    <span class="float-right text-muted">
                      {{user.role}}
                    </span>
                  </p>
                  <p class="clearfix">
                    <span class="float-left">
                      E-mail
                    </span>
                    <span class="float-right text-muted">
                      {{ user.get_username }}
                    </span>
                  </p>
                  <p class="clearfix">
                    <span class="float-left">
                      Dépot
                    </span>
                    <span class="float-right text-muted">
                      {{user.warehouse}}
                    </span>
                  </p>
                  <p class="clearfix">
                    <span class="float-left">
                      Manager de dépot
                    </span>
                    <span class="float-right text-muted">
                      {{user.is_manager}}
                    </span>
                  </p>
                </div>                                                       
              </div>
            </div>
            <div class="col-lg-8 pl-lg-5">
              <div class="d-flex justify-content-between">
                <div>
                  <h3>{{user.pseudo}}</h3>
                  <div class="d-flex align-items-center">
                    <h5 class="mb-0 mr-2 text-muted"></h5>
                  </div>
                </div>
              </div>
              
              <div class="mt-4 py-2 border-top ">
                <ul class="nav profile-navbar">
               
                </ul>
              </div>
              <div class="profile-feed">
                <div class="d-flex align-items-start profile-feed-item">
               
                  <div class="ml-4">
                    <h6>
                      Notes :
                    </h6>
                    <p>
                      {{user.notes}}
                    </p>
                  
                  </div>
                </div>

               
              </div>
            </div>
          </div> 
          <a href="{% url 'accounts:edituser' user.pk %}">
          <button type="submit" style="float:right;" class="btn btn-primary mr-2">Edit</button> </a>
        </div>
      </div>
    </div>
  </div>
  <!-- main-panel ends -->
</div>

{% endblock content %}