config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('core.urls')), 
    path ('', include('accounts.urls')), 
    path ('', include('inventory.urls')), 
    path ('', include('order.urls')), 

    # path('markdownx/', include('markdownx.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# else:
#     urlpatterns += path('taksit-admin/', admin.site.urls),

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required, permission_required
from .views import IndexView
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

inventory/urls.py
from django.urls import path
from . import views 
from .views import AddProductView, ProductListView, ProductUpdateView,ProductDeleteView,  ProductDetailView
from .views import AddWarehouseView, WarehouseListView, WarehouseUpdateView
from .views import AddCategoryView, AddBrandView, BrandListView,  CategoryListView
from .views import  EditWarehouseItemView, WarehouseDetailView
from .views import ProductAnalyticsView, WarehouseAnalyticsView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'inventory'

urlpatterns = [ 
  
   #PRODUCT
   path('productlist', login_required(ProductListView.as_view()), name='productlist'),
   path('editproduct/<int:pk>/', login_required(ProductUpdateView.as_view()), name="editproduct"),
   path('productdetail/<int:pk>/', login_required(ProductDetailView.as_view()), name="productdetail"),
   path('productdelete/<int:pk>/', login_required(ProductDeleteView.as_view()), name="productdelete"),
   path('brandlist', login_required(BrandListView.as_view()), name='brandlist'),
   path('addbrand', login_required(AddBrandView.as_view()), name="addbrand"),
   path('addcategory', login_required(AddCategoryView.as_view()), name="addcategory"),
   path('categorylist', login_required(CategoryListView.as_view()), name='categorylist'),
   path('addproduct', login_required(AddProductView.as_view()), name="addproduct"),
   
   #WAREHOUSE 
   path('warehouselist', login_required(WarehouseListView.as_view()), name='warehouselist'),
   path('addwarehouse', login_required(AddWarehouseView.as_view()), name="addwarehouse"),
   path('editwarehouse/<int:pk>/', login_required(WarehouseUpdateView.as_view()), name="editwarehouse"),
   path('warehousedetail/<int:pk>/', login_required(WarehouseDetailView.as_view()), name="warehousedetail"),
   ##Warehouseitem
   path('editwarehouseitem/<int:pk>/', login_required(EditWarehouseItemView.as_view()), name="editwarehouseitem"),
   
   ## analytics 
   path('productanalytics', login_required(ProductAnalyticsView.as_view()), name='productanalytics'),
   path('warehouseanalytics', login_required(WarehouseAnalyticsView.as_view()), name='warehouseanalytics'),

]

inventory/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext as _
# from django.conf import settings
# Create your models here.
from django.utils.text import slugify
import order
from django.db.models.signals import post_save, pre_save
from location.models import Commune
class WareHouseManager(models.Manager):
    def principale(self):
        return WareHouse.objects.filter(is_default=True).first()

class Brand(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nom')
    actif = models.BooleanField(verbose_name='actif', default=True)
    class Meta:
        verbose_name = _("Brand")
        verbose_name_plural = _("Brands")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("inventoy:brand_detail", kwargs={"pk": self.pk})

class Category(MPTTModel):
    name  = models.CharField( max_length=150, verbose_name='Nom')
    slug  = models.SlugField( max_length=150, unique= True, verbose_name='URL')
    order  = models.IntegerField(verbose_name='ordre', null=True, blank=True)
    actif = models.BooleanField(verbose_name='actif', default=True)
    icon  = models.ImageField(upload_to='images/categories', null=True, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')    

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categorys"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("inventoy:category_detail", kwargs={"pk": self.pk})

class Product(models.Model):
    name         = models.CharField( max_length=200, verbose_name='Nom')
    upc           = models.CharField( max_length=200, verbose_name='code article')
    slug         = models.SlugField( max_length=150, unique= True, verbose_name='URL')
    reference    = models.CharField( max_length=200, verbose_name='Référence / code a bar', unique=True, blank=True, null=True)
    category     = TreeForeignKey(Category, verbose_name="Catégorie",related_name="products" ,on_delete=models.CASCADE, blank=True, null=True)
    brand        = models.ForeignKey(Brand, related_name="brand_products", on_delete=models.CASCADE, blank=True, null=True)
    text         = models.TextField(verbose_name='petit text', blank=True, null=True)
    price        = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    old_price    = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Ancien prix",blank=True, null=True)
    buy_price    = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="prix d'achat",blank=True, null=True)
    actif        = models.BooleanField(verbose_name='actif', default=True) 
    new          = models.BooleanField(verbose_name='Nouveau', default=False)
    created      = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("inventoy:product_detail", kwargs={"pk": self.pk})


class WareHouse(models.Model):
    name         = models.CharField( max_length=200, verbose_name='Nom du revendeur/point de stockage')
    address      = models.CharField( max_length=200, verbose_name='address')
    actif        = models.BooleanField(verbose_name='actif', default=False)
    is_default   = models.BooleanField(verbose_name='Dépot principale', default=False)
    commune      = models.ForeignKey(Commune, on_delete=models.SET_NULL, null=True, blank=True)
    created      = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    objects     = models.Manager()
    centrale     = WareHouseManager()

    class Meta:
        verbose_name = _("WareHouse")
        verbose_name_plural = _("WareHouses")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("inventoy:wareHouse_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.is_default = True
        update_default = WareHouse.objects.all().exclude(id=self.id).update(is_default=False)
        super(WareHouse, self).save(*args, **kwargs)


class WareHouseItem(models.Model):
    product   = models.ForeignKey(Product, related_name="product", on_delete=models.CASCADE, blank=True, null=True)
    quantity  = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    location = models.ForeignKey(WareHouse, related_name="depot", on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = _("WareHouseItem")
        verbose_name_plural = _("WareHouseItems")

    def __str__(self):
        return  str(self.product)

    def get_absolute_url(self):
        return reverse("inventoy:wareHouseItem_detail", kwargs={"pk": self.pk})




def product_created_signal(sender, instance, created,**kwargs):
    if created:
        warehouses = WareHouse.objects.all()
        for warehouse in warehouses:
            item = WareHouseItem.objects.get_or_create(product= instance, location=warehouse, quantity=0)
        instance.save()
post_save.connect(product_created_signal, sender=Product)

location/models.py
from django.db import models



class Wilaya(models.Model):
    name           = models.CharField(max_length=40, verbose_name="Wilaya", unique=True)
    relai_delivery = models.DecimalField( max_digits=8, verbose_name="Livraison point de Relais", decimal_places=2, default=0)
    home_delivery  = models.DecimalField( max_digits=10, verbose_name="Livraison à domicile", decimal_places=2, default=0)
    active         = models.BooleanField(default=True, verbose_name="Livraison Active")
    created        = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated        = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)
    class Meta:
        verbose_name = "Wilaya"
        verbose_name_plural = "1. Wilayas"

    def __str__(self):
        return self.name

class Commune(models.Model):
    wilaya = models.ForeignKey(Wilaya, on_delete=models.CASCADE, verbose_name="Wilaya")
    name = models.CharField(max_length=30, verbose_name="Commune")
    # active = models.BooleanField(default=True, verbose_name="Livraison Active")
    created      = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)
    class Meta:
        verbose_name = "Commune"
        verbose_name_plural = "2. Communes"        

    def __str__(self):
        return self.name

inventory/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product, Brand, Category, WareHouseItem, WareHouse


class AddProductForm(ModelForm) :
    class Meta: 
        model = Product 
        fields = ('name','upc','reference','category','brand','text','price','old_price','buy_price','actif','new',) 
        
class AddBrandForm(ModelForm) :
    class Meta: 
        model = Brand 
        fields = '__all__' 

class AddCategoryForm(ModelForm) :
    class Meta: 
        model = Category
        fields = '__all__' 

class AddWareHouseForm(ModelForm) :
    class Meta: 
        model = WareHouse
        fields = '__all__' 

class AddWareHouseItemForm(ModelForm) :
    class Meta: 
        model = WareHouseItem
        fields = '__all__' 

inventory/templates/delete-product.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Produit</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Produit
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Suppression du produit</h4>
                <form action="{% url 'inventory:productdelete' product.pk %}" method="post"  class="form-sample">
                    {% csrf_token %}
                  <h6 class="card-description">
                    Etes-vous sûr de vouloir supprimer &nbsp; {{product.name}} ? 
                  </h6>  
                 
                
                  <button type="submit" class="btn btn-primary mr-2">Soumettre </button>
                  
                </form>
               
              </div>
             
            </div>
          
          </div>


      
      
      
      
      
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}

inventory/templates/edit-product.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Produit</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Produit
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Modification du produit</h4>
                <form action="{% url 'inventory:editproduct' product.pk %}" method="post"  class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                   
                  </p>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_name">Intitulé</label>
                        <div class="col-sm-9">
                          <input  type="text" name="name"  id="id_name"  required="" class="form-control" value="{{product.name}}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_upc">Code article:</label>
                        <div class="col-sm-9">
                          <input type="text" name="upc"  id="id_upc" required="" maxlength="200" class="form-control" value="{{product.upc}}">
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="id_reference">Référence / code a bar:</label>
                        <div class="col-sm-9">
                        <input type="text" name="reference"   id="id_reference" required=""  maxlength="200" class="form-control" value="{{product.reference}}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_slug">URL:</label>
                          <div class="col-sm-9">
                          <input type="text" name="slug"  required=""  maxlength="200" maxlength="150" id="id_slug" class="form-control" value="{{product.slug}}">
                          </div>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">	
                        <label class="col-sm-3 col-form-label" for="id_category">Marque :</label>
                        <div class="col-sm-9">
                          <select class="form-control"  name="brand" id="id_brand" value="{{product.brand}}"> 
                            <option value="{{product.brand}}" selected="">{{product.brand}}</option>
                            {% for brand in brands %}
                                <option value="{{brand.id}}">{{brand.name}}</option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>
                     
                    <div class="col-md-6">
                      <div class="form-group row">	
                        <label class="col-sm-3 col-form-label" for="id_category">Catégorie :</label>
                        <div class="col-sm-9">
                          <select class="form-control"  name="category" id="id_category" value="{{product.category}}"> 
                            <option value="{{product.category}}" selected="">{{product.category}}</option>
                            {% for category in categorys %}
                                <option value="{{category.id}}">{{category.name}}</option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>
                   
                    <div class="col-md-6">
                      <div class="form-group row">
                            <div class="col-sm-4">
                                <div class="form-check form-check-primary">
                                    <label class="form-check-label" for="id_actif">
                                     Actif 
                                      <input type="checkbox" class="form-check-input"  checked="" name="actif" id="id_actif" value="{{product.actif}}"> 
                                    <i class="input-helper"></i></label>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-check form-check-primary">
                                    <label class="form-check-label" for="id_new">
                                        Nouveau 
                                      <input type="checkbox" class="form-check-input"  checked="" name="new" id="id_new" value="{{product.new}}"> 
                                    <i class="input-helper"></i></label>
                                </div>
                            </div>
                      </div>
                    </div>
                  </div>
                  <p class="card-description">
                    
                  </p>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row"> 
                        <label class="col-sm-3 col-form-label" class="required" for="id_price">Prix:</label>
                        <div class="col-sm-9">
                          <input type="number" name="price"  step="1" required="" id="id_price" class="form-control" value="{{product.price}}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label" for="id_buy_price">Prix d'achat:</label>
                          <div class="col-sm-9">
                            <input type="number" name="buy_price"  step="1" required="" id="id_buy_price" class="form-control" value="{{product.buy_price}}">
                          </div>
                        </div>
                      </div>
                  </div>
                  {% comment %} <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row"> 
                          <label class="col-sm-3 col-form-label" class="required" for="id_old_price">Ancien prix:</label>
                          <div class="col-sm-9">
                            <input type="number" name="old_price" value="0" step="1" required="" id="id_old_price" class="form-control">
                          </div>
                        </div>
                      </div>
                  </div> {% endcomment %}
                  <div class="row">
                        <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Notes :</label>
                            <div class="col-sm-9">
                            <textarea class="form-control" id="id_text" name="text" cols="40" rows="10" value="{{product.text}}"> {{product.text}}</textarea>
                            </div>
                        </div>
                        </div>
                  </div>
                  <button type="submit" class="btn btn-primary mr-2">Soumettre </button>
                  
                </form>
               
              </div>
             
            </div>
          
          </div>


      
      
      
      
      
        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}

inventory/templates/edit-warehouse.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Dépots</title>
{% endblock %}
 
      <div class="content-wrapper">
          <div class="page-header">
              <h3 class="page-title">
                Dépots
              </h3>
          </div>
          <div class="col-12 grid-margin">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Ajout des dépots</h4>
                <form action="{% url 'inventory:addwarehouse' %}"  method="post"  class="form-sample">
                    {% csrf_token %}
                  <p class="card-description">
                  </p>
                  <div class="row">
                        <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label" for="id_name">Intitulé :</label>
                            <div class="col-sm-9">
                            <input  type="text" name="name"  id="id_name"  required="" class="form-control">
                            </div>
                        </div>
                        </div>
                        <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label" for="id_upc">Adresse :</label>
                            <div class="col-sm-9">
                            <input type="text" name="address"  id="id_address" required="" maxlength="200" class="form-control">
                            </div>
                        </div>
                        </div>
                  </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                </form>
              </div>
            </div>
          
          </div>

        </div>
    <!-- main-panel ends -->
  </div>

  {% endblock content %}

inventory/templates/product-list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block title %}
<title>Produit</title>
{% endblock %}
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
          Produit
        </h3>
    </div> 
    <div class="col-md-6 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-0">Total</h4>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="d-inline-block pt-3">
                        <div class="d-md-flex">
                            <h2 class="mb-0">{{ product_count }} </h2>
                            
                        </div>
                    </div>
                    <div class="d-inline-block">
                        <i class=" fas  fa-cubes text-info icon-lg"></i>                                    
                    </div>
                </div>
            </div>
        </div>
    </div> 
    <div class="row">
        <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                    <div class="d-md-flex justify-content-between align-items-center">
                        <tr class="row">
                            <td >
                                <input type="text" class="form-control"  placeholder="reference"></td>
                            <td >
                                    <input type="date" class="form-control"  placeholder="date debut"></td>
                            <td >
                                <input type="date" class="form-control"  placeholder="date fin"></td>
                            <td >
                                <select class="form-control"  name="category" id="id_category"> 
                                {% for category in categorys %}
                                    <option  value="{{category.id}}">{{category.name}}</option>
                                {% endfor %}
                                </select>
                            </td>
                            <td >
                                <select class="form-control"  name="brand" id="id_brand"> 
                                {% for brand in brands %}
                                    <option value="{{brand.id}}">{{brand.name}}</option>
                                {% endfor %}
                                </select>
                            </td>
                            
                            <td >
                                <button type="submit" class="btn btn-primary mr-2"> <i class="fas fa-filter"></i></button>
                            </td>
                        </tr>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <a href="{% url 'inventory:addproduct' %}" > <button type="submit" class="btn btn-primary mr-2" style="float:right;">+ Produit</button><a>
                <a href="{% url 'inventory:brandlist' %}"> <button type="submit" class="btn btn-primary mr-2" style="float:right;">Marques</button><a>
                <a href="{% url 'inventory:categorylist' %}"> <button type="submit" class="btn btn-primary mr-2" style="float:right;">Catégories</button><a> 
          <h4 class="card-title">Liste des produits</h4>
          <div class="row">
            <div class="col-12">
              <div class="table-responsive">
                <div id="order-listing_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                    <div >
                 
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="order-listing" class="table dataTable no-footer" role="grid" aria-describedby="order-listing_info">
                                        <thead>
                                            <tr role="row">
                                                <th>Intitulé </th>
                                                <th>Référence</th>
                                                <th>Catégorie</th>
                                                <th>Marque</th>
                                                <th>Prix</th>
                                                <th>Prix d'achat</th>
                                                <th >Actif</th>
                                                <th >Nouveau</th>
                                                <th></th>
                                                <th >Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody> 
                                        {% for product in products %}
                                        <tr role="row" class="odd">
                                                <td >{{product.name}}</td>
                                                <td>{{product.reference}}</td>
                                                <td>{{product.category}}</td>
                                                <td>{{product.brand}}</td>
                                                <td>{{product.price}} DZD</td>
                                                <td> {{product.buy_price}} DZD</td>
                                                <td>{{product.actif}}</td>
                                                <td>{{product.new}}</td>
                                                <td></td>
                                                <td>
                                                <a href="{% url 'inventory:productdetail' product.pk %}">
                                                <button class="btn btn-outline-primary">Voir</button></a>
                                                <a href="{% url 'inventory:editproduct' product.pk %}">
                                                <button class="btn btn-outline-primary">Modifier</button></a>
                                                <a href="{% url 'inventory:productdelete' product.pk %}">
                                                    <button class="btn btn-outline-primary">Supprimer</button></a>
                                                </td>
                                            </tr>    
                                        {% endfor %}
                                        </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                                        <div class="row">
                                            <div class="col-sm-12 col-md-5">
                                                <div class="dataTables_info" id="order-listing_info" role="status" aria-live="polite">Showing 1 to 10 of 10 entries</div>
                                            </div>
                                            <div class="col-sm-12 col-md-7">
                                                <div class="dataTables_paginate paging_simple_numbers" id="order-listing_paginate">
                                                    <ul class="pagination">
                                                        <li class="paginate_button page-item previous disabled" id="order-listing_previous">
                                                            <a href="#" aria-controls="order-listing" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                                                        </li>
                                                        <li class="paginate_button page-item active"><a href="#" aria-controls="order-listing" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                                                        <li class="paginate_button page-item next disabled" id="order-listing_next"><a href="#" aria-controls="order-listing" data-dt-idx="2" tabindex="0" class="page-link">Next</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                    </div>
                                </div>
                                </div>
                            </div>


    <!-- main-panel ends -->
</div>

{% endblock content %}