accounts/urls.py
from django.urls import path
from .views import SignupView, SignupsuccessView
from django.contrib.auth import views as auth_views
from .froms import AuthenticationForm
from django.contrib.auth.decorators import login_required, permission_required
from .views import UserView, UserUpdateView
app_name= 'accounts'

urlpatterns = [
  
 path('signup/', SignupView.as_view(), name="signup"),
 path('signup_success/', SignupsuccessView.as_view(), name="signup_success"),
 path('login/', auth_views.LoginView.as_view(template_name="login.html",form_class=AuthenticationForm,),name="login",),
 path('logout/' , auth_views.LogoutView.as_view(), name= 'logout' ),
 path('userdetail', login_required(UserView.as_view()), name="userdetail"),
 path('edituser/<int:pk>/', login_required(UserUpdateView.as_view()), name="edituser"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('core.urls')), 
    path ('', include('accounts.urls')), 
    path ('', include('inventory.urls')), 
    path ('', include('order.urls')), 

    # path('markdownx/', include('markdownx.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# else:
#     urlpatterns += path('taksit-admin/', admin.site.urls),

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required, permission_required
from .views import IndexView
app_name= 'core'

urlpatterns = [
  
  path('', login_required(IndexView.as_view()), name='index'),
   ]

inventory/urls.py
from django.urls import path
from . import views 
from .views import AddProductView, ProductListView, ProductUpdateView,ProductDeleteView,  ProductDetailView
from .views import AddWarehouseView, WarehouseListView, WarehouseUpdateView
from .views import AddCategoryView, AddBrandView, BrandListView,  CategoryListView
from .views import  EditWarehouseItemView, WarehouseDetailView
from .views import ProductAnalyticsView, WarehouseAnalyticsView
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'inventory'

urlpatterns = [ 
  
   #PRODUCT
   path('productlist', login_required(ProductListView.as_view()), name='productlist'),
   path('editproduct/<int:pk>/', login_required(ProductUpdateView.as_view()), name="editproduct"),
   path('productdetail/<int:pk>/', login_required(ProductDetailView.as_view()), name="productdetail"),
   path('productdelete/<int:pk>/', login_required(ProductDeleteView.as_view()), name="productdelete"),
   path('brandlist', login_required(BrandListView.as_view()), name='brandlist'),
   path('addbrand', login_required(AddBrandView.as_view()), name="addbrand"),
   path('addcategory', login_required(AddCategoryView.as_view()), name="addcategory"),
   path('categorylist', login_required(CategoryListView.as_view()), name='categorylist'),
   path('addproduct', login_required(AddProductView.as_view()), name="addproduct"),
   
   #WAREHOUSE 
   path('warehouselist', login_required(WarehouseListView.as_view()), name='warehouselist'),
   path('addwarehouse', login_required(AddWarehouseView.as_view()), name="addwarehouse"),
   path('editwarehouse/<int:pk>/', login_required(WarehouseUpdateView.as_view()), name="editwarehouse"),
   path('warehousedetail/<int:pk>/', login_required(WarehouseDetailView.as_view()), name="warehousedetail"),
   ##Warehouseitem
   path('editwarehouseitem/<int:pk>/', login_required(EditWarehouseItemView.as_view()), name="editwarehouseitem"),
   
   ## analytics 
   path('productanalytics', login_required(ProductAnalyticsView.as_view()), name='productanalytics'),
   path('warehouseanalytics', login_required(WarehouseAnalyticsView.as_view()), name='warehouseanalytics'),

]

order/urls.py
from django.urls import path
from . import views 
from .views import client_order_create,client_order_edit, add_new_item,clientOrderBcListView,clientOrderFfListView,clientOrderBlListView, ClientOrderDetailView, ClientCustomPrintableView, warehouse_order_create, WarehouseOrderBcListView, WarehouseOrderFfListView,  WarehouseOrderBlListView, WarehouseOrderDetailView, WarehouseCustomPrintableView, create_supplier_order, SupplierOrderBcListView, SupplierOrderBrListView, AddSupplierView,SupplierListView, SupplyOrderDetailView, SupplierCustomPrintableView , DeliveryListView, warehouse_order_edit, htmx_order_bc_list
from django.contrib.auth.decorators import login_required, permission_required
app_name= 'order' 
 
urlpatterns = [
  
   path('add_new_item', add_new_item, name="add_new_item"),
   #commandes interne  
   path('warehouse_order_create', login_required(warehouse_order_create), name="warehouse_order_create"),
   path('warehouse_order_edit/<int:pk>', login_required(warehouse_order_edit), name="warehouse_order_edit"),
   path('warehouse_order_bc_list', login_required(WarehouseOrderBcListView.as_view()), name="warehouse_order_bc_list"),
   path('htmx_order_bc_list', login_required(htmx_order_bc_list), name="htmx_order_bc_list"),
   path('warehouse_order_ff_list', login_required(WarehouseOrderFfListView.as_view()), name="warehouse_order_ff_list"),
   path('warehouse_order_bl_list', login_required(WarehouseOrderBlListView.as_view()), name="warehouse_order_bl_list"),
   path('warehouseorder_detail/<int:pk>/', login_required(WarehouseOrderDetailView.as_view()), name="warehouseorder_detail"),
   path('warehouseorderpdf/<int:pk>/', login_required(WarehouseCustomPrintableView.as_view()), name="warehouseorderpdf"),
   #commandes fournisseur 
   path('create_supplier_order', login_required(create_supplier_order), name="create_supplier_order"),
   path('addsupplier', login_required(AddSupplierView.as_view()), name="addsupplier"),
   path('supplierlist', login_required(SupplierListView.as_view()), name="supplierlist"),
   path('supplier_order_bc_list', login_required(SupplierOrderBcListView.as_view()), name="supplier_order_bc_list"),
   path('supplier_order_br_list', login_required(SupplierOrderBrListView.as_view()), name="supplier_order_br_list"),
   path('supplyorder_detail/<int:pk>/', login_required(SupplyOrderDetailView.as_view()), name="supplyorder_detail"),
   path('supplyorderpdf/<int:pk>/', login_required(SupplierCustomPrintableView.as_view()), name="supplyorderpdf"),
   #commandes client 
   path('create_client_order', login_required(client_order_create), name="client_order_create"),
   path('client_order_edit', login_required(client_order_edit), name="client_order_edit"),
   path('client_order_bc_list', login_required(clientOrderBcListView.as_view()), name="client_order_bc_list"),
   path('client_order_ff_list', login_required(clientOrderFfListView.as_view()), name="client_order_ff_list"),
   path('client_order_bl_list', login_required(clientOrderBlListView.as_view()), name="client_order_bl_list"),
   path('clientorder_detail/<int:pk>/', login_required(ClientOrderDetailView.as_view()), name="clientorder_detail"),
   path('clientorderpdf/<int:pk>/', login_required(ClientCustomPrintableView.as_view()), name="clientorderpdf"),
   ## livraison  
   path('delivery_list', login_required(DeliveryListView.as_view()), name="delivery_list"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block title %}
<title>base</title>
{% endblock %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Stock</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/iconfonts/font-awesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.addons.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
</head>
{% include 'navbar.html' %}
{% include 'sidebar.html' %}

<body>
            {%block scripts%}
            {%endblock scripts%}
            {% block content %}
            
            {% endblock content %}

  <!-- plugins:js -->
  <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'vendors/js/vendor.bundle.addons.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->

  <!-- inject:js -->
  <script src="{% static 'vendors/js/off-canvas.js' %}"></script>
  <script src="{% static 'vendors/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'vendors/js/misc.js' %}"></script>
  <script src="{% static 'vendors/js/settings.js' %}"></script>
  <script src="{% static 'vendors/js/todolist.js' %}"></script>
  <script src="{% static 'vendors/js/formpickers.js' %}"></script>
  <script src="{% static 'vendors/js/form-addons.js' %}"></script>
  <script src="{% static 'vendors/js/x-editable.js' %}"></script>
  <script src="{% static 'vendors/js/dropify.js' %}"></script>
  <script src="{% static 'vendors/js/dropzone.js' %}"></script>
  <script src="{% static 'vendors/js/jquery-file-upload.js' %}"></script>
  <script src="{% static 'vendors/js/formpickers.js' %}"></script>
  <script src="{% static 'vendors/js/form-repeater.js' %}"></script>
  <script src="{% static 'vendors/js/chart.js' %}"></script>
  <script src="{% static 'vendors/js/dashboard.js' %}"></script>
  <!-- End custom js for this page-->
{% block extrasj %}

{% endblock extrasj %}

 <!-- Vendor JS Files -->
 {% comment %} <script src="assets/vendor/aos/aos.js"></script>
 <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
 <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
 <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
 <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
 <script src="assets/vendor/waypoints/noframework.waypoints.js"></script>
 <script src="assets/vendor/php-email-form/validate.js"></script> {% endcomment %}

 <!-- Template Main JS File -->
 <script src="{% static 'js/main.js' %}"></script>
 <script src="https://unpkg.com/htmx.org@1.5.0" ></script>
 <!-- <script type="text/javascript" src="{% static "js/site-base.js" %}"></script> -->
 <!-- <script type="text/javascript" src="{% static "CACHE/js/awesome.8dd1a2872443.js" %}" charset="utf-8"></script> -->
 <script>
     document.body.addEventListener('htmx:configRequest', (event) => {
         event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
     })
 </script>
</body>


</html>

templates/navbar.html
{% load static %}
<div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row default-layout-navbar">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href="/"><img src="{% static 'images/logo.png' %}" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="/"><img src="{% static 'images/logo-mini.png' %}" alt="logo"/></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="fas fa-bars"></span>
          </button>
          <!-- message -->
          {% if messages %}
          <ul class="navbar-nav messages" style="margin-left:400px;">
                  {% for message in messages %}
                  <h6 {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }} </h6>
                  {% endfor %}
          </ul> 
           <!-- message -->
          {% endif %} 
     
          <ul class="navbar-nav navbar-nav-right"> 
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                <i class="fas fa-bell mx-0"></i>
                <span class="count">16</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                <a class="dropdown-item">
                  <p class="mb-0 font-weight-normal float-left">You have 16 new notifications
                  </p>
                  <span class="badge badge-pill badge-warning float-right">View all</span>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-danger">
                      <i class="fas fa-exclamation-circle mx-0"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-medium">Application Error</h6>
                    <p class="font-weight-light small-text">
                      Just now
                    </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-warning">
                      <i class="fas fa-wrench mx-0"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-medium">Settings</h6>
                    <p class="font-weight-light small-text">
                      Private message
                    </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-info">
                      <i class="far fa-envelope mx-0"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-medium">New user registration</h6>
                    <p class="font-weight-light small-text">
                      2 days ago
                    </p>
                  </div>
                </a>
              </div> 
            </li>
          
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                <img src="{{user.display_picture}}" alt="profile"/>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                <a class="dropdown-item"  href="{% url 'accounts:userdetail' %}">
                  <i class="fas fa fa-user-circle text-primary"></i> 
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"  href="{% url 'accounts:logout' %}">
                  <i class="fas fa-power-off text-primary"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
      
        </div>
      </nav>
      <!-- partial -->

    

templates/sidebar.html
{% load static %}



    <div class="container-fluid page-body-wrapper">

          <!-- partial:../../partials/_settings-panel.html -->
          <div class="theme-setting-wrapper">
            <div id="settings-trigger"><i class="fas fa-fill-drip"></i></div>
            <div id="theme-settings" class="settings-panel">
              <i class="settings-close fa fa-times"></i>
              <p class="settings-heading">SIDEBAR SKINS</p>
              <div class="sidebar-bg-options selected" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
              <div class="sidebar-bg-options" id="sidebar-dark-theme"><div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
              <p class="settings-heading mt-2">HEADER SKINS</p>
              <div class="color-tiles mx-0 px-4">
                <div class="tiles primary"></div>
                <div class="tiles success"></div>
                <div class="tiles warning"></div>
                <div class="tiles danger"></div>
                <div class="tiles info"></div>
                <div class="tiles dark"></div>
                <div class="tiles default"></div>
              </div>
            </div>
          </div>

     <!-- partial:../../partials/_sidebar.html -->
     <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="profile-image">
                <img  src="{{user.display_picture}}" alt="image"/>
              </div>
              <div class="profile-name">
                <p class="name">
                  {{ user.get_username }}
                </p>
                <p class="designation">
                  
                </p>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/" >
              <i class="fa fa-home menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#editors" aria-expanded="false" aria-controls="editors">
              <i class="fas fa-chart-line menu-icon"></i>
              <span class="menu-title">Analytics</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="editors">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"><a class="nav-link" href="{% url 'inventory:productanalytics' %}">Produits</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'inventory:warehouseanalytics' %}">Dépots</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#charts" aria-expanded="false" aria-controls="charts">
              <i class="fas fa-boxes menu-icon"></i>
              <span class="menu-title">Produits</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="charts">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'inventory:productlist' %}">Liste des produits</a></li>
              </ul>
              </div>
          </li>
          <li class="nav-item"> 
            <a class="nav-link" data-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
              <i class="fas fa-warehouse menu-icon"></i>
              <span class="menu-title">Dépots</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="tables">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'inventory:warehouselist' %}">Liste des dépots</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">
              <i class="fas fa-dolly-flatbed menu-icon"></i>
              <span class="menu-title">Commandes interne</span> 
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="icons">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:warehouse_order_bc_list' %}">Bon de commande</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:warehouse_order_ff_list' %}">Facture finale</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:warehouse_order_bl_list' %}">Bon de livraison</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-advanced" aria-expanded="false" aria-controls="ui-advanced">
              <i class="fas fa-solid fa-cart-plus menu-icon"></i>
              <span class="menu-title">Commandes fournisseur</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-advanced">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:supplier_order_bc_list' %}">Bon de commande</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:supplier_order_br_list' %}">Bon de récéption</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">
              <i class="fas fa-solid fa-cart-plus menu-icon"></i>
              <span class="menu-title">Commandes client</span> <i class="fa-solid fa-cart-arrow-up"></i>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="form-elements">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:client_order_bc_list' %}">Bon de commande</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:client_order_ff_list' %}">Facture finale</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:client_order_bl_list' %}">Bon de livraison</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#maps" aria-expanded="false" aria-controls="maps">
              <i class="fas fa-truck menu-icon"></i>
              <span class="menu-title">Livraisons</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="maps">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'order:delivery_list' %}">Liste des livraison</a></li>
              </ul>
            </div>
          </li>
          
        </ul>
      </nav>
      <!-- partial -->